# Generated by Django 3.1.1 on 2020-09-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('title', models.CharField(default='', max_length=255)),
                ('available_inventory', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
