# Generated by Django 3.1.1 on 2020-10-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201001_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_inventory',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='', max_length=255),
        ),
    ]
