# Generated by Django 3.1.1 on 2020-10-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201001_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available_inventory',
            new_name='stock',
        ),
    ]
